service:
  name: podium-api

plugins:
  - serverless-webpack
  - serverless-offline

provider:
  name: aws
  runtime: nodejs8.10
  stage: ${opt:stage, 'dev'}
  region: us-east-1

functions:
  api:
    handler: app/router.handler
    name: ${self:service}-api-${self:provider.stage}
    description: Podium API
    events:
      - http:
          path: api/{any+}
          method: ANY

custom:
  webpack:
    webpackConfig: ./webpack.config.js
    includeModules: true
    packager: 'npm'